config/routes.rb
Rails.application.routes.draw do
  resources :scoreboards
  devise_for :users

  root to: "scoreboards#index"

end

app/models/scoreboard.rb
class Scoreboard < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :scoreboards
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scoreboards_controller.rb
class ScoreboardsController < ApplicationController
  before_action :set_scoreboard, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /scoreboards
  # GET /scoreboards.json
  def index
    @scoreboards = Scoreboard.all
  end

  # GET /scoreboards/1
  # GET /scoreboards/1.json
  def show
  end

  # GET /scoreboards/new
  def new
    @scoreboard = current_user.scoreboards.new
  end

  # GET /scoreboards/1/edit
  def edit
  end

  # POST /scoreboards
  # POST /scoreboards.json
  def create
    @scoreboard = current_user.scoreboards.new(scoreboard_params)

    respond_to do |format|
      if @scoreboard.save
        format.html { redirect_to @scoreboard, notice: 'Scoreboard was successfully created.' }
        format.json { render :show, status: :created, location: @scoreboard }
      else
        format.html { render :new }
        format.json { render json: @scoreboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scoreboards/1
  # PATCH/PUT /scoreboards/1.json
  def update
    respond_to do |format|
      if @scoreboard.update(scoreboard_params)
        format.html { redirect_to @scoreboard, notice: 'Scoreboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @scoreboard }
      else
        format.html { render :edit }
        format.json { render json: @scoreboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scoreboards/1
  # DELETE /scoreboards/1.json
  def destroy
    @scoreboard.destroy
    respond_to do |format|
      format.html { redirect_to scoreboards_url, notice: 'Scoreboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scoreboard
      @scoreboard = Scoreboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scoreboard_params
      params.require(:scoreboard).permit(:user_id,
                                          :alaska,
                                          :arizona,
                                          :arkansas,
                                          :alabama,
                                          :california,
                                          :colorado,
                                          :connecticut,
                                          :delaware,
                                          :district_of_columbia,
                                          :florida, 
                                          :georgia,
                                          :hawaii,
                                          :idaho,
                                          :illinois,
                                          :indiana,
                                          :iowa,
                                          :kansas,
                                          :kentucky,
                                          :louisiana,
                                          :maine,
                                          :maryland,
                                          :massachusetts,
                                          :michigan,
                                          :minnesota,
                                          :mississippi,
                                          :missouri,
                                          :montana,
                                          :nebraska,
                                          :nevada,
                                          :new_hampshire,
                                          :new_jersey,
                                          :new_mexico,
                                          :new_york,
                                          :north_carolina,
                                          :north_dakota,
                                          :ohio,
                                          :oklahoma,
                                          :oregon,
                                          :pennsylvania,
                                          :puerto_rico,
                                          :rhode_island,
                                          :south_carolina,
                                          :south_dakota,
                                          :tennessee,
                                          :texas,
                                          :utah,
                                          :vermont,
                                          :virginia,
                                          :washington,
                                          :west_virginia,
                                          :wisconsin,
                                          :wyoming
                                          )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scoreboards_helper.rb
module ScoreboardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roadtriplp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>
 Logged in as <strong><%= current_user.email %></strong>.
 <%= link_to 'Edit profile', edit_user_registration_path %> |
 <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
 <%= link_to "Sign up", new_user_registration_path %> |
 <%= link_to "Login", new_user_session_path %>
<% end %>
</body>
<%= yield %>
</html>

app/views/scoreboards/_form.html.erb
<%= simple_form_for(@scoreboard) do |f| %>
  <%= f.error_notification %>

<div class="form-inputs">
    <%= f.input :alaska %>
	<%= f.input :arizona %>
	<%= f.input :arkansas %>
	<%= f.input :alabama %>
	<%= f.input :california %>
	<%= f.input :colorado %>
	<%= f.input :connecticut %>
	<%= f.input :delaware %>
	<%= f.input :district_of_columbia %>
	<%= f.input :florida %>	
	<%= f.input :georgia %>
	<%= f.input :hawaii %>
	<%= f.input :idaho %>
	<%= f.input :illinois %>
	<%= f.input :indiana %>
	<%= f.input :iowa %>
	<%= f.input :kansas %>
	<%= f.input :kentucky %>
	<%= f.input :louisiana %>
	<%= f.input :maine %>
	<%= f.input :maryland %>
	<%= f.input :massachusetts %>
	<%= f.input :michigan %>
	<%= f.input :minnesota %>
	<%= f.input :mississippi %>
	<%= f.input :missouri %>
	<%= f.input :montana %>
	<%= f.input :nebraska %>
	<%= f.input :nevada %>
	<%= f.input :new_hampshire %>
	<%= f.input :new_jersey %>
	<%= f.input :new_mexico %>
	<%= f.input :new_york %>
	<%= f.input :north_carolina %>
	<%= f.input :north_dakota %>
	<%= f.input :ohio %>
	<%= f.input :oklahoma %>
	<%= f.input :oregon %>
	<%= f.input :pennsylvania %>
	<%= f.input :puerto_rico %>
	<%= f.input :rhode_island %>
	<%= f.input :south_carolina %>
	<%= f.input :south_dakota %>
	<%= f.input :tennessee %>
	<%= f.input :texas %>
	<%= f.input :utah %>
	<%= f.input :vermont %>
	<%= f.input :virginia %>
	<%= f.input :washington %>
	<%= f.input :west_virginia %>
	<%= f.input :wisconsin %>
	<%= f.input :wyoming %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scoreboards/edit.html.erb
<h1>Editing Scoreboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @scoreboard %> |
<%= link_to 'Back', scoreboards_path %>

app/views/scoreboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scoreboards</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scoreboards.each do |scoreboard| %>
      <tr>
        <td><%= scoreboard.user_id %></td>
        <td><%= link_to 'Show', scoreboard %></td>
        <td><%= link_to 'Edit', edit_scoreboard_path(scoreboard) %></td>
        <td><%= link_to 'Destroy', scoreboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scoreboard', new_scoreboard_path %>

app/views/scoreboards/new.html.erb
<h1>New Scoreboard</h1>

<%= render 'form' %>

<%= link_to 'Back', scoreboards_path %>

app/views/scoreboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @scoreboard.user_id %>
</p>

<%= link_to 'Edit', edit_scoreboard_path(@scoreboard) %> |
<%= link_to 'Back', scoreboards_path %>